// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecsygfhekmsvfprsqcwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjc3lnZmhla21zdmZwcnNxY3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4NjkzNjQsImV4cCI6MjA3ODQ0NTM2NH0.u0eo-aiW0cuJQ23AxWxVs78XMOd6aFaCxPfBsosKJVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});