// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwcozpyuhfzaacxhdbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d2NvenB5dWhmemFhY3hoZGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDI1MTMsImV4cCI6MjA2OTE3ODUxM30.DtvOHbxmB2PdaoR7F4a8cmxb1y0FCqRxjgSZzq9MvHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});